# permissions for end users to view locusttests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: locusttest-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: test
    app.kubernetes.io/part-of: test
    app.kubernetes.io/managed-by: kustomize
  name: locusttest-viewer-role
rules:
- apiGroups:
  - locust.io
  resources:
  - locusttests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - locust.io
  resources:
  - locusttests/status
  verbs:
  - get
